chore!: remove support for Telescope builtin file_browser
jvgrootveld/telescope-zoxide pull request #19
Opened 2023-02-11 03:17 UTC by axieax

- [x] Removed support for Telescope builtin file_browser
- [x] Added section to README for using https://github.com/nvim-telescope/telescope-file-browser.nvim

2023-04-22 11:49 UTC, axieax commented
Hi @jvgrootveld could you please review this? Thanks!

2024-07-23 14:00 UTC, jvgrootveld commented
Ty for your contribution. I was a little absent lately due to different things. I just want to let everyone know will check all Open issues and PR's shortly.

2024-07-31 06:18 UTC, jvgrootveld commented on README.md
> +            vim.cmd("edit " .. selection.path)
You changed more than described in your commit or PR. Why did you change the `vim.cmd` commands?

2024-07-31 06:20 UTC, jvgrootveld commented on lua/telescope/_extensions/zoxide/config.lua
> -    ["<C-t>"] = {
Curious why you removed this default mapping as well? It is also not described in the comment or PR message of why.

2024-07-31 06:26 UTC, jvgrootveld commented
@axieax I reviewed your PR, and I find it awesome that you created a PR to remove an (now) not-working feature and updated the readme with an alternative if others used it. I'm not sure about all the other changes in this PR which are also not described.

Could you explain these extra changes? To merge this feature asap I would recommend to change the PR so that only picker is removed and the Readme is updated.

I could just change it myself but I want to give you the choice to be added as a contributor 😄

2024-07-31 06:36 UTC, jvgrootveld requested changes
@axieax I reviewed your PR, and I find it awesome that you created a PR to remove an (now) not-working feature and updated the readme with an alternative if others used it. I'm not sure about all the other changes in this PR which are also not described.

Could you explain these extra changes? To merge this feature asap I would recommend to change the PR so that only picker is removed and the Readme is updated.

I could just change it myself but I want to give you the choice to be added as a contributor 😄

2024-08-08 06:38 UTC, jvgrootveld commented
@axieax I notice you are busy. I will wait for your change till next week. After that I will create a copy of your fork and update the code myself.

I am not sure if you will be added as a contributor if I update it but I still will mention you in the PR.

2024-08-28 06:20 UTC, jvgrootveld commented on lua/telescope/_extensions/zoxide/config.lua
> -    ["<C-t>"] = {
Updated it myself :)

2024-08-28 06:20 UTC, jvgrootveld commented on README.md
> +            vim.cmd("edit " .. selection.path)
Updated it myself :)

2024-08-28 06:28 UTC, merged