feat(main): notification message
jvgrootveld/telescope-zoxide pull request #20
Opened 2023-03-04 00:01 UTC by CMOISDEAD

Changed the way in which the user is informed that the directory has changed to `vim.notify`

2024-07-23 14:01 UTC, jvgrootveld commented
Ty for your contribution. I was a little absent lately due to different things. I just want to let everyone know will check all Open issues and PR's shortly.

2024-07-31 06:33 UTC, jvgrootveld requested changes
@CMOISDEAD I reviewed your PR, good change!

To merge this feature asap I would recommend to change the PR so that the only change is the `print` to `vim.notify` without all the formatting changes.

I could just change it myself but I want to give you the choice to be added as a contributor 😄

2024-07-31 06:33 UTC, jvgrootveld commented on lua/telescope/_extensions/zoxide/config.lua
> +        -- print("Directory changed to " .. selection.path)
Could you remove the commented out code?

2024-07-31 06:33 UTC, jvgrootveld commented on lua/telescope/_extensions/zoxide/config.lua
Could you remove your formatting changes so that the only change is the `print` to `vim.notify` ?

2024-08-01 00:59 UTC, CMOISDEAD commented on lua/telescope/_extensions/zoxide/config.lua
Sorry for the late reply! Here's the update you asked for 😄

2024-08-01 01:00 UTC, CMOISDEAD commented
Sorry for the late reply! Here's the update you asked for 😄

2024-08-01 07:31 UTC, jvgrootveld commented on lua/telescope/_extensions/zoxide/config.lua
"Late" :') it's been 1 day.

Still seeing a lot of unwanted formatting changes. Could you revert those so that the PR only contains the print change?

![image](https://github.com/user-attachments/assets/ef3ed481-3de0-4b9a-ae50-3617550ee80c)

2024-08-01 19:28 UTC, CMOISDEAD commented
Oh right, I removed that unnecessary identation :)

2024-08-02 06:21 UTC, jvgrootveld approved these changes

2024-08-02 06:23 UTC, merged